lorisleiva/laravel-actions

- src/EventDispatcherDecorator.php
Fix Class 'Lorisleiva\Actions\EventDispatcherDecorator' not found on composer install, update and dump-autoload etc. for case sensitive file systems, caused by a typo in the vendor name of the package.
> Fix Class 'Lorisleiva\Actions\EventDispatcherDecorator' not found

- src/ActionServiceProvider.php
Ensure that EventDispatcherDecorator is used for future calls to Event::listen().
Fixes an issue where Event::listen() would use the standard EventDispatcher in stead of EventDispatcherDecorator.
Other ServiceProviders (e.g. PassportServiceProvider) may use the Event facade before this package is booted, resulting in the standard EventDispatcher being cached and used in all future calls to Event::listen().
Clearing the cached instance allows an EventDispatcherDecorator instance to be resolved and cached the next time the Event Facade is used.
> Clear cached Event Facade instance

- README.md
Some info about using the new prepareForValidation method, an that it is the same convention from Laravel FormRequests.
> Added documentation for prepareForValidation method

- src/EventDispatcherDecorator.php
I notice that in every request `laravel-actions` were instantiating every single listener in order to verify if it was a sub-class of `Lorisleiva\Actions\Action`. 
Using PHP's `is_a ` to verify if the listener is an `Action` in the `EventDispatcherDecorator` might reduce the overhead of resolving it from the application container along with all of its dependency in every request.
> Avoid instantiating every listener to check if is a subclass of Action.

- src/Action.php
- tests/Actions/SimpleCalculatorWithHandleDefaults.php
- tests/RegistersActionsTest.php
- tests/RunsAsObjectsTest.php
Fixes #61 
- Always call `resolveAttributesFromConstructor` in the constructor to account for possible
attributes in handle signature.
- Treat attributes in `handle` and attributes in `getAttributesFromConstructor` separately.
- Normalize return value to `$this` in `resolveAttributesFromConstructor`
> Fixes ignored default values in handle method.

- src/Concerns/HasTelescopeTags
When Laravel Telescope records an entry for a Job/Event/Exception, it automatically associates the record with tags for all the Eloquent models included in the object.
These tags can then be monitored, making it easy to filter records related to one specific model.
This doesn't work for Actions, since the included models are dynamic attributes and not hard-coded properties.
Adding this trait to an Action fixes that, since Telescope will call the object's `tags` method if one exists.
This is just a proof of concept, since I'm a new Telescope user. I just thought it might be useful to others.
It *should* identify every model present in the attributes, whether they're single models, arrays or collections. If the models have any relationships loaded, their tags are also included recursively …
> Add HasTelescopeTags trait

- src/Concerns/SerializesModels.php
- tests/SerializesModelsTest.php
Closes #55.
This PR adds additional prep work during `sleep` and `wakeup` methods to correctly serialize models and collections within the attributes array.
These changes will ensure the payload of jobs remain as small as possible.
These changes _may_ be breaking in some cases. Previously a model would have been serialized like a regular class, meaning should you have changed some model attributes and not persisted them then the job would be run with those un-persisted changes. After these changes, the model will be fetched from the database, fresh, when the model is unserialized. It's unlikely but a consideration non-the-less.
> Ensure models are serialized correctly within attributes

- src/Concerns/ResolvesMethodDependencies.php
As explained here: https://php.watch/versions/8.0/deprecated-reflectionparameter-methods#getClass
Works also with my local Laravel project based on PHP 7.4
> Fix deprecation error with PHP 8

- src/ActionRequest.php
- src/ActionValidator.php
- src/AttributeValidator.php
- src/Concerns/DecorateActions.php
- src/Concerns/ValidateActions.php
- src/Concerns/WithAttributes.php
- src/Decorators/ControllerDecorator.php
- tests/AsActionWithValidatedAttributesTest.php
- tests/AsControllerAndObjectTest.php
- tests/AsControllerTest.php
- tests/AsControllerWithAuthorizeAndRulesTest.php
- tests/AsControllerWithCustomFailuresTest.php
- tests/AsControllerWithCustomRedirectAndErrorBagTest.php
- tests/AsControllerWithCustomValidationDataTest.php
- tests/AsControllerWithCustomValidatorTest.php
- tests/AsControllerWithMiddlewareTest.php
- tests/AsControllerWithPolicyResponsesTest.php
- tests/AsControllerWithPrepareForValidationTest.php
- tests/AsControllerWithRoutesTest.php
- tests/AsControllerWithValidatedAttributesTest.php
- tests/AsControllerWithValidationMessagesTest.php
- tests/AsControllerWithValidatorCallbacksTest.php
- tests/AsObjectWithAuthorizeAndRulesTest.php
- tests/AsObjectWithValidatedAttributesTest.php
Since Laravel Actions v2 was released, a common feature request has been to offer **authorization and validation for every pattern** and not just controllers.
In Laravel Actions v1, this was made possible by having unified attributes in the `Action` class. When building v2, I decided to make Actions as less intrusive as possible allowing any class to be executed as a controller, job, etc. This meant dropping the unified attributes and providing a simpler, more intuitive API using `asController`, `asJob`, etc. methods.
Whilst I still believe this was the right way to go, I can also understand the value of having a set of unified attributes that can be validated and accessed from anywhere. This is why I decided to provide a new optional `WithAttributes` trait.
This PR provides a new …
> Add optional support for unified attributes

- src/Console/stubs/action.stub
Compare https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/stubs/test.stub. The generation still works, I didn't find a test for it.
Related to #116.
> Refactoring stub variables to match Laravel's pattern

- src/Console/MakeActionCommand.php
Add `Illuminate\Console\Concerns\CreatesMatchingTest` to `Lorisleiva\Actions\Console\MakeActionCommand` to match framework generator command patterns. 
Closes #153
> Allow for matching tests to be created on make:action

- src/Decorators/JobDecorator.php
- tests/AsJobWithFailureTest.php
When a Laravel job fails, Laravel supports cleaning up from that job by defining a `failed()` function on the job class.
See Laravel documentation here: https://laravel.com/docs/8.x/queues#cleaning-up-after-failed-jobs
This PR adds support for a new function on the Laravel Action called `jobFailed(Throwable $e)`. If a job fails, this function will be called to provide an opportunity to clean up from the job failure.
See #161.
I don't have much experience writing tests, and would appreciate any feedback on writing a better test if needed.
> Support for new function jobFailed(Throwable $e)

- src/Decorators/JobDecorator.php
- tests/AsJobWithUniqueHintedAsJobDecoratorTest.php
> Allow any job decorator sub-class to be type-hinted as a first argument

- src/Concerns/AsObject.php
- tests/AsObjectTest.php
This refers to #173 and adds the methods `SomeAction::runIf($boolean)` and `SomeAction::runUnless($boolean)`. There are also some tests. The implementation is analogous to the `AsJob` trait.
As these changes are backward compatible I think it warrants only a minor version bump.
> Conditional Object runs added

- .github/workflows/run-tests.yml
- composer.json
- src/Concerns/AsController.php
- tests/AsControllerWithMiddlewareTest.php
- tests/AsJobSerializedTest.php
Since version `9.35.0` of the Laravel framework, a PR was merged that changed the way controller middleware were resolved which lead to action middleware not being resolved.
A follow-up PR was implemented on `laravel/framework` (https://github.com/laravel/framework/pull/44590) to enable Laravel Actions to keep its current behaviour whilst making sure the new behaviour from 9.35.0 is not broken.
The goal of this PR is to perform the final update on Laravel Actions which leverages the latest PR on the framework.
Note that this fix will only work once a new version of the framework is published (anything that comes after `9.35.1`).
Fix #199.
> Fix controller middleware not resolving (#199)

- src/Decorators/CommandDecorator.php
see [#205](https://github.com/lorisleiva/laravel-actions/issues/205)
That pull request makes possible to access Illuminate\Console\Command::$components protected property from asCommand method.
```php
namespace App\Actions;
use Illuminate\Console\Command;
class ConsoleTestAction extends Action {
public string $commandSignature = 'test-action';
public function asCommand(Command $command): void {
$command->getComponents()->info('Done!');
}
}
```
**Result:**
I dont know if is the best choice.
Maybe the best way is to open a pull request on laravel repo.
> Make InteractsWithIO::$components protected property accessible on CommandDecorator

- src/Concerns/ValidateActions.php
Although the `ActionRequest::validated` method accepts the `$key` and `$default` parameters (for `FormRequest` compatibility), these parameters are not used as implemented in Laravel ([#36807](https://github.com/laravel/framework/pull/36807)).
This PR fixes that.
Previous Behavior:
```php
public function handle(ActionRequest $request) {
$validated = $request->validated(); // Returns an array
$password = $request->validated('password'); // Still returns an array
}
```
New Behavior:
```php
public function handle(ActionRequest $request) {
$validated = $request->validated(); // Returns an array
$password = $request->validated('password'); // Still returns the validated `password` field's value
}
```
> Implement option to get a validated input using key

- src/ActionManager.php
- src/Concerns/AsJob.php
- tests/ActionManagerTest.php
- tests/AsJobTest.php
- tests/AsJobWithAssertionsTest.php
- tests/Helpers.php
- tests/Pest.php
- tests/Stubs/CustomJobDecorator.php
- tests/Stubs/CustomUniqueJobDecorator.php
This PR adds the ability to define custom job decorator classes. These custom classes will then get used when using an action as a job. The default implementation is to use the existing `JobDecorator` and `UniqueJobDecorator` classes, so this should be a backwards compatible change.
In order to change the decorator classes, two new methods were added to the `ActionManager`.
- `ActionManager::useJobDecorator(string $jobDecoratorClass)` changes the decorator class that gets used when an action gets turned into a non-unique job
- `ActionManager::useUniqueJobDecorator(string $uniqueJobDecoratorClass)` changes the decorator that gets used when an action gets turned into a unique job
Apart from that, the only non-test code that needed be changed were the `makeJob`, `makeUniqueJob`, and …
> Add option to configure custom job decorator classes

- src/ActionManager.php
- src/ActionServiceProvider.php
Fixes #136 
This PR seems to fix the issue when using listeners with an application running on Octane where it calls `handle` instead of the `asListener` method.
```
App\Actions\User\SetupCompleted::handle(): Argument #1 ($user) must be of type App\Models\User, App\Events\UserUpdated given, called in /.../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 424
```
We encountered this issue on listeners that **were not queued (i.e. not implementing `ShouldQueue`)**.
After some lengthy debugging, it seemed that the `app()->extend(..` callback in `ActionManager::extend` method was not actually getting called once the listener was resolved when running on Octane. So I tried to figure out which container instance it should be using. 
Basically reverted the changes made …
> Fix Octane Event using handle instead of asListener

- src/Decorators/ListenerDecorator.php
- tests/AsListenerWithShouldQueueTest.php
This  PR adds support for the below functionality that exists on traditional listeners.
> #### Conditionally Queueing Listeners
> 
> Sometimes, you may need to determine whether a listener should be queued based on some data that are only available at runtime. To accomplish this, a `shouldQueue` method may be added to a listener to determine whether the listener should be queued. If the `shouldQueue` method returns `false`, the listener will not be executed:
> ```php
>     <?php
> 
>     namespace App\Listeners;
> 
>     use App\Events\OrderCreated;
>     use Illuminate\Contracts\Queue\ShouldQueue;
> 
>     class RewardGiftCard implements ShouldQueue
>     {
>         /**
>          * Reward a gift card to the customer.
>          */
>         public function handle(OrderCreated $event): …
```
> Add support for listener shouldQueue method

- src/ActionManager.php
Currently, the limit of backtrace frames is set to 10 and cannot be changed. It would be great if it would be possible to increase the limit for custom design patterns (e.g., I would like to use it in combination with Lighthouse). Anyway, while debugging the same I was wondering whether the first 9 frames could be skipped because those all belong to `laravel` or `laravel-actions` and thus the time could rather be spent on real potential matches.
> feat: increase backtrace frame limit

- src/ActionManager.php
This PR allows custom patterns to be registered via:
```php
$this->app->extend(ActionManager::class, function (ActionManager $actionManager) {
$actionManager->registerDesignPattern(new FooBarDesignPattern());
return $actionManager;
});
```
> feat: allow custom design patterns

- .github/workflows/php-cs-fixer.yml
- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- phpunit.xml.dist
- tests/AsJobWithBatchTest.php
Only support two latest major versions of Laravel as per Support Policy https://laravel.com/docs/11.x/releases#support-policy
Remove Laravel 9 and PHP 8.0 support
> Support Laravel 11

- src/Decorators/JobDecorator.php
- tests/AsJobConfiguredWithMethodsTest.php
- tests/AsJobConfiguredWithPropertiesTest.php
This enables the user to configure the job using `->setDeleteWhenMissingModels()` within `configureJob()` or by setting `$jobDeleteWhenMissingModels = true`
> Handle $deleteWhenMissingModels on JobDecorator

- composer.json
When you run PHP 8.1, and you try `composer install` the following error will appear:
Laravel 10 [needs](https://packages.tools/testbench#version-compatibility) Orchestra Testbench 8.
This PR fixes that compatibility.
The branch name is not entirely correct, but you get the point. 😋
👋 Edwin
> Fix Orchestra Laravel 10 compatibility

- src/Concerns/AsObject.php
- tests/AsActionTest.php
Remove static return type. See https://github.com/lorisleiva/laravel-actions/pull/285#issuecomment-2296463178
> Remove return type for make()

- src/Concerns/AsJob.php
- tests/AsJobTest.php
- tests/AsJobWithAssertionsTest.php
- tests/Helpers.php
When I am testing that actions are pushed correctly, I almost always want to check the parameters that it is pushed with.
Currently it is a little cumbersome to check the params, as they are passed in as an array.
```php
SendPodcastPublishedEmail::dispatch($user, $podcast);
// currently...
SendPodcastPublishedEmail::assertPushed(fn ($a, $params) => $params[0]->is($user) && $params[1]->is($podcast));
```
Additionally, the thing I want to check is in the second argument so I have an unused variable.
If we spread the params into the callback we can use type safety to check we have the correct type and shortcut the param check.
```php
SendPodcastPublishedEmail::dispatch($user, $podcast);
// assert by closure
SendPodcastPublishedEmail::assertPushedWithParams(fn (User $u, Podcast $p) => …
```
> Add assert with params convenience methods 

- src/ActionManager.php
Fixes deprecation error in PHP 8.4
> Fixed implicitly nullable parameter

- src/Exceptions/MissingCommandSignatureException.php
Fixes
```
PHP Deprecated:  Lorisleiva\Actions\Exceptions\MissingCommandSignatureException::__construct(): Implicitly marking parameter $previous as nullable is deprecated, the explicit nullable type must be used instead in ./src/Exceptions/MissingCommandSignatureException.php on line 10
```
> Fix php8.4 deprecated notices
